[project]
name = "hydra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = ["flytekit>=1.14.6", "numpy>=2.2.2", "pystorms>=1.0.0"]
